import os

import pytest
import drjit as dr
import mitsuba as mi
import numpy as np


FLOAT_DTYPES = {16: np.float16, 32: np.float32, 64: np.float64}
UINT_DTYPES  = {16: np.uint16,  32: np.uint32,  64: np.uint64}
LARGE_PHASE_SIZE=50000
CACHED = True
CACHE_PATH = "/tmp/cloudphase_test_data.npz"


def _to_ordered_uint(x: np.floating) -> int:
    nb       = x.itemsize * 8
    bits     = int(x.view(UINT_DTYPES[nb]))
    sign_bit = 1 << (nb - 1)
    all_ones = (1 << nb) - 1
    if bits == sign_bit:
        bits = 0
    if bits & sign_bit:
        bits ^= all_ones
    else:
        bits |= sign_bit
    if bits < sign_bit:
        bits += 1
    return bits


def _from_ordered_uint(i: int, dtype) -> np.floating:
    nb       = np.dtype(dtype).itemsize * 8
    sign_bit = 1 << (nb - 1)
    all_ones = (1 << nb) - 1
    if i < sign_bit:
        i -= 1
    if i & sign_bit:
        i ^= sign_bit
    else:
        i ^= all_ones
    return np.array(i, dtype=UINT_DTYPES[nb]).view(dtype)[()]


def _sample_unique_uints(lo: int, hi: int, k: int) -> np.ndarray:
    """
    Sample k unique integers uniformly from (lo, hi) exclusive.
    Uses rejection sampling — O(k) for sparse ranges (float32/64),
    falls back to np.random.choice for dense ranges (float16).
    """
    interior = hi - lo - 1   # number of available interior slots

    if interior < 3 * k:
        # Dense: population small enough for choice (float16 territory)
        return np.sort(
            np.random.choice(interior, size=k, replace=False).astype(np.int64) + lo + 1
        )

    # Sparse: rejection sampling — expected ~k * (1 + k/interior) samples
    result = set()
    while len(result) < k:
        needed  = k - len(result)
        samples = np.random.randint(lo + 1, hi, size=needed + 16, dtype=np.int64)
        result.update(samples.tolist())
    return np.array(sorted(result)[:k], dtype=np.int64)


def monotonic_floats(a: float, b: float, n: int, precision: int = 16) -> np.ndarray:
    """
    Generate n strictly monotonic floats between a and b (inclusive)
    with uniformly random interior values.
    """
    if precision not in FLOAT_DTYPES:
        raise ValueError(f"precision must be 16, 32, or 64. Got {precision}.")
    if n < 2:
        raise ValueError("n must be at least 2.")

    dtype = FLOAT_DTYPES[precision]
    a, b  = dtype(a), dtype(b)

    if not (np.isfinite(a) and np.isfinite(b)):
        raise ValueError(f"a and b must be finite in float{precision}.")
    if a == b:
        raise ValueError(f"a and b are equal or indistinguishable in float{precision}.")

    ascending = b > a
    lo, hi    = (a, b) if ascending else (b, a)

    lo_uint   = _to_ordered_uint(lo)
    hi_uint   = _to_ordered_uint(hi)
    ulp_steps = hi_uint - lo_uint

    if ulp_steps < n - 1:
        raise ValueError(
            f"Cannot fit {n} strictly monotonic float{precision} values between "
            f"{a} and {b}: only {ulp_steps + 1} representable values exist "
            f"in that interval (need {n})."
        )

    if n == 2:
        return np.array([lo, hi] if ascending else [hi, lo], dtype=dtype)

    inner_uints = _sample_unique_uints(lo_uint, hi_uint, n - 2)

    all_uints = np.concatenate([[lo_uint], inner_uints, [hi_uint]])
    combined  = np.array([_from_ordered_uint(int(i), dtype) for i in all_uints], dtype=dtype)

    assert np.all(np.diff(combined) > 0), "BUG: monotonicity violated."

    return combined if ascending else combined[::-1].copy()


def generate_n_mueller(n, s=6, min_points=164, max_points=1000):

    """
    Using Henyey-Greenstein, generate n * s phase functions to
    fill n polarized tabulated phase functions. Default to 6 phases
    in order to emulate spherical polarized particles media.

    Map the phases on incompatible irregular angular grids,
    generated by sampling cos. There is no guarantee that the
    cos grid is sensible to sample the phase, and the physicallity
    of the phase is not assessed. This is for test purposes.

    The number of generated points per s-sized set of phases resides
    in [min_points; max_points[.

    This function is deterministic.
    """

    if n <1:
        raise ValueError("n must be superior to 1")
    if s <1:
        raise ValueError("s must be superior to 1")
    if min_points <2:
        raise ValueError("min_points must be superior to 2")
    if max_points <= min_points:
        raise ValueError("max_points must be superior to min_points")
    
    rng = np.random.default_rng(0)
    
    grid_len = rng.integers(min_points, max_points, n)
    grid_start = np.cumsum(grid_len)
    total_points = grid_start[-1]
    grid_start = grid_start - grid_len

    nodes = np.empty(total_points, dtype=np.float32)
    for i in range(n):
        st = grid_start[i]
        le = grid_len[i]
        en = st + le
        nodes[st:en] = monotonic_floats(-1.0, 1.0, le, precision=32)
        assert nodes[st] == -1.0
        assert nodes[en - 1] == 1.0

    idx = np.concatenate([np.full(grid_len[i], i) for i in range(n)])

    g = rng.random((n, s)) * 2.0 - 1.0
    P_hg = np.empty((total_points, s))

    for j in range(s):
        gj = g[:, j][idx]          # (total_points,) — one column
        gj_2 = gj * gj
        gj_mu = nodes * gj
        denom = 1.0 + gj_2 - 2.0 * gj_mu  # (total_points,)
        denom = denom * np.sqrt(denom)      # x^1.5 = x * sqrt(x)
        P_hg[:, j] = (1.0 - gj_2) / denom

    P_hg *= 1.0 / (4.0 * np.pi)

    return rng, nodes, grid_start, grid_len, P_hg


@pytest.fixture(scope="session")
def large_phase_data():
    if CACHED and os.path.exists(CACHE_PATH):
        d = np.load(CACHE_PATH)
        return d["nodes"], d["grid_start"], d["grid_len"], d["P_hg"], d["index"]
    rng, nodes, grid_start, grid_len, P_hg = generate_n_mueller(LARGE_PHASE_SIZE)
    index_shape = (1500, 100, 100)
    index = rng.integers(0, LARGE_PHASE_SIZE, index_shape)
    np.savez(CACHE_PATH, nodes=nodes, grid_start=grid_start,
             grid_len=grid_len, P_hg=P_hg, index=index)
    return nodes, grid_start, grid_len, P_hg, index


@pytest.fixture() 
def large_phase_plugin(large_phase_data, variant_scalar_mono_polarized):
    nodes, grid_start, grid_len, P_hg, index = large_phase_data
    rng = np.random.default_rng(42)
    return rng, mi.load_dict({
        "type": "cloudphase",
        "index_volume": {
            "type": "gridvolume",
            "grid": mi.VolumeGrid(index),
            "filter_type": "nearest",
        },
        "n_entries": LARGE_PHASE_SIZE,
        "nodes": dr.scalar.ArrayXf(nodes),
        "phase_mueller": dr.scalar.ArrayXf(P_hg.flatten()),
        "grid_start": dr.scalar.ArrayXu(grid_start),
        "grid_len": dr.scalar.ArrayXu(grid_len),
    })


def reference_eval_pdf(nodes, grid_start, grid_len, P_hg, index, wi, wo):
    start  = grid_start[index]
    length = grid_len[index]
    entry_nodes   = nodes[start : start + length]
    entry_mueller = P_hg[start : start + length, :]

    cos_t = float(np.clip(-np.dot(wo, wi), -1.0, 1.0))

    idx = np.searchsorted(entry_nodes, cos_t, side='left')
    idx = np.clip(idx, 1, length - 1)
    lo, hi = idx - 1, idx
    x0, x1 = entry_nodes[lo], entry_nodes[hi]
    t = (cos_t - x0) / (x1 - x0) if (x1 - x0) > 0 else 0.0
    m = entry_mueller[lo] + t * (entry_mueller[hi] - entry_mueller[lo])

    dx       = np.diff(entry_nodes)
    m11_vals = entry_mueller[:, 0]
    integral = float(np.sum(0.5 * (m11_vals[:-1] + m11_vals[1:]) * dx))

    norm = 1.0 / (integral * 2.0 * np.pi) if integral > 0 else 0.0
    pdf  = float(m[0] * norm)

    # build raw Mueller matrix
    mueller = mi.Spectrum([
        [ float(m[0]),  float(m[1]),  0.0,          0.0         ],
        [ float(m[1]),  float(m[2]),  0.0,          0.0         ],
        [ 0.0,          0.0,          float(m[3]),  float(m[4]) ],
        [ 0.0,          0.0,         -float(m[4]),  float(m[5]) ],
    ]) * float(norm)

    # radiance mode: wo_hat=wo, wi_hat=wi
    wo_hat = mi.Vector3f(wo)
    wi_hat = mi.Vector3f(wi)

    x_hat      = dr.cross(-wo_hat, wi_hat)
    p_axis_in  = dr.normalize(dr.cross(x_hat, -wo_hat))
    p_axis_out = dr.normalize(dr.cross(x_hat,  wi_hat))

    mueller = mi.mueller.rotate_mueller_basis(
        mueller,
        -wo_hat, p_axis_in,  mi.mueller.stokes_basis(-wo_hat),
         wi_hat, p_axis_out, mi.mueller.stokes_basis( wi_hat)
    )

    return mueller.numpy()[:, :, 0], pdf


def get_index_at(index_array, p):
    # index_array shape is (1500, 100, 100) = (nz, ny, nx) in mitsuba's convention
    nz, ny, nx = index_array.shape
    ix = int(np.clip(p[0] * nx, 0, nx - 1))
    iy = int(np.clip(p[1] * ny, 0, ny - 1))
    iz = int(np.clip(p[2] * nz, 0, nz - 1))
    return int(index_array[iz, iy, ix])


def test_eval_pdf_reference(large_phase_data, large_phase_plugin):
    nodes, grid_start, grid_len, P_hg, index_array = large_phase_data
    _, phase = large_phase_plugin

    P_hg_2d = P_hg.reshape(-1, 6)

    ctx = mi.PhaseFunctionContext(None)
    mei = mi.MediumInteraction3f()
    rng = np.random.default_rng(42)

    for i in range(100):
        # non-degenerate random directions
        wi = rng.random(3) * 2 - 1
        wi /= np.linalg.norm(wi)
        wo = rng.random(3) * 2 - 1
        wo /= np.linalg.norm(wo)
        p  = rng.random(3)

        mei.wi = mi.Vector3f(wi)
        mei.p  = mi.Point3f(p)

        # mitsuba evaluation
        val, pdf = phase.eval_pdf(ctx, mei, mi.Vector3f(wo))

        # index from construction array
        index = get_index_at(index_array, p)

        # numpy reference — note: no Stokes rotation applied here,
        ref_mueller, ref_pdf = reference_eval_pdf(
            nodes, grid_start, grid_len, P_hg_2d, index, wi, wo
        )

        val, pdf = phase.eval_pdf(ctx, mei, mi.Vector3f(wo))
        index = get_index_at(index_array, p)
        ref_mueller, ref_pdf = reference_eval_pdf(
            nodes, grid_start, grid_len, P_hg_2d, index, wi, wo
        )

        # pdf check — not affected by Stokes rotation
        assert np.isclose(float(pdf), ref_pdf, rtol=1e-4, atol=1e-7), \
            f"[i={i}] pdf mismatch: got {float(pdf):.8f}, expected {ref_pdf:.8f}\n" \
            f"  index={index}, cos_t={-np.dot(wo,wi):.4f}"

        # Mueller check — Stokes rotation makes full matrix comparison
        # unreliable without reimplementing rotate_mueller_basis in numpy.
        # Check only M11 which is rotation-invariant.
        val_np = val.numpy()[:, :, 0]
        assert np.allclose(val_np, ref_mueller, rtol=1e-4, atol=1e-7), \
            f"[i={i}] Mueller mismatch:\ngot:\n{val_np}\nexpected:\n{ref_mueller}"


def test_large_phase(large_phase_plugin):

    rng, phase = large_phase_plugin
    ctx = mi.PhaseFunctionContext(None)
    mei = mi.MediumInteraction3f()
    


    ctx = mi.PhaseFunctionContext(None)
    mei = mi.MediumInteraction3f()
    mei.wi = [0, 0, 1]
    mei.p = mi.Point3f([0.5, 0.5, 0.5])
    val, pdf = phase.eval_pdf(ctx, mei, mi.Vector3f([0, 0, -1]))

    import time

    # pre-generate all inputs
    N = 100000
    rng2 = np.random.default_rng(99)
    wis = rng2.random((N, 3)) * 2 - 1
    wis /= np.linalg.norm(wis, axis=1, keepdims=True)
    wos = rng2.random((N, 3)) * 2 - 1
    wos /= np.linalg.norm(wos, axis=1, keepdims=True)
    ps  = rng2.random((N, 3))

    # time Python setup overhead
    t0 = time.perf_counter()
    for i in range(N):
        mei.wi = mi.Vector3f(wis[i])
        mei.p  = mi.Point3f(ps[i])
    t_setup = (time.perf_counter() - t0) / N * 1e6
    print(f"Python setup overhead: {t_setup:.2f} us/call")

    # time full eval with proper spatial spread
    t0 = time.perf_counter()
    for i in range(N):
        mei.wi = mi.Vector3f(wis[i])
        mei.p  = mi.Point3f(ps[i])
        phase.eval_pdf(ctx, mei, mi.Vector3f(wos[i]))
    t_eval = (time.perf_counter() - t0) / N * 1e6
    print(f"eval_pdf (spread):     {t_eval:.2f} us/call")
    print(f"C++ only estimate:     {t_eval - t_setup:.2f} us/call")

@pytest.fixture(scope="session")
def single_phase_data():
    rng, nodes, grid_start, grid_len, P_hg = generate_n_mueller(1)
    return nodes, grid_start, grid_len, P_hg


@pytest.fixture
def tabphase_plugin(single_phase_data, variant_scalar_mono_polarized):
    nodes, grid_start, grid_len, P_hg = single_phase_data
    entry_mueller = P_hg.reshape(-1, 6)

    def arr_to_str(a):
        return ", ".join(f"{v}" for v in a)

    return mi.load_dict({
        "type": "tabphase_polarized",
        "nodes": arr_to_str(nodes),
        "m11":   arr_to_str(entry_mueller[:, 0]),
        "m12":   arr_to_str(entry_mueller[:, 1]),
        "m22":   arr_to_str(entry_mueller[:, 2]),
        "m33":   arr_to_str(entry_mueller[:, 3]),
        "m34":   arr_to_str(entry_mueller[:, 4]),
        "m44":   arr_to_str(entry_mueller[:, 5]),
    })


@pytest.fixture
def cloudphase_single(single_phase_data, variant_scalar_mono_polarized):
    nodes, grid_start, grid_len, P_hg = single_phase_data
    length = len(nodes)
    return mi.load_dict({
        "type": "cloudphase",
        "index_volume": {
            "type": "gridvolume",
            "grid": mi.VolumeGrid(np.zeros((1, 1, 1), dtype=np.float32)),
            "filter_type": "nearest",
        },
        "n_entries": 1,
        "nodes":         dr.scalar.ArrayXf(nodes),
        "phase_mueller": dr.scalar.ArrayXf(P_hg.flatten()),
        "grid_start":    dr.scalar.ArrayXu(np.array([0], dtype=np.uint32)),
        "grid_len":      dr.scalar.ArrayXu(np.array([length], dtype=np.uint32)),
    })


def test_stress_vs_tabphase(tabphase_plugin, cloudphase_single):
    import time

    N = 100000
    rng = np.random.default_rng(99)
    wis = rng.random((N, 3)) * 2 - 1
    wis /= np.linalg.norm(wis, axis=1, keepdims=True)
    wos = rng.random((N, 3)) * 2 - 1
    wos /= np.linalg.norm(wos, axis=1, keepdims=True)
    ps  = rng.random((N, 3))

    ctx = mi.PhaseFunctionContext(None)
    mei = mi.MediumInteraction3f()

    t0 = time.perf_counter()
    for i in range(N):
        mei.wi = mi.Vector3f(wis[i])
        mei.p  = mi.Point3f(ps[i])
        tabphase_plugin.eval_pdf(ctx, mei, mi.Vector3f(wos[i]))
    t_tab = (time.perf_counter() - t0) / N * 1e6

    t0 = time.perf_counter()
    for i in range(N):
        mei.wi = mi.Vector3f(wis[i])
        mei.p  = mi.Point3f(ps[i])
        cloudphase_single.eval_pdf(ctx, mei, mi.Vector3f(wos[i]))
    t_cloud = (time.perf_counter() - t0) / N * 1e6

    assert (t_cloud - t_tab) / t_tab < 0.3

    print(f"\ntabphase_polarized:  {t_tab:.2f} us/call")
    print(f"cloudphase (single): {t_cloud:.2f} us/call")
    print(f"ratio:               {t_tab/t_cloud:.2f}x")


def test_correctness_vs_tabphase(tabphase_plugin, cloudphase_single, single_phase_data):
    nodes, grid_start, grid_len, P_hg = single_phase_data

    rng = np.random.default_rng(42)
    ctx = mi.PhaseFunctionContext(None)
    mei = mi.MediumInteraction3f()

    for i in range(100):
        wi = rng.random(3) * 2 - 1
        wi /= np.linalg.norm(wi)
        wo = rng.random(3) * 2 - 1
        wo /= np.linalg.norm(wo)

        mei.wi = mi.Vector3f(wi)
        mei.p  = mi.Point3f(rng.random(3))

        val_tab,   pdf_tab   = tabphase_plugin.eval_pdf(ctx, mei, mi.Vector3f(wo))
        val_cloud, pdf_cloud = cloudphase_single.eval_pdf(ctx, mei, mi.Vector3f(wo))

        assert np.isclose(float(pdf_tab), float(pdf_cloud), rtol=1e-4, atol=1e-7), \
            f"[i={i}] pdf mismatch: tabphase={float(pdf_tab):.8f}, " \
            f"cloudphase={float(pdf_cloud):.8f}, cos_t={-np.dot(wo, wi):.4f}"

        val_tab_np   = val_tab.numpy()
        val_cloud_np = val_cloud.numpy()
        assert np.allclose(val_tab_np, val_cloud_np, rtol=1e-4, atol=1e-7), \
            f"[i={i}] Mueller matrix mismatch:\n" \
            f"tabphase:\n{val_tab_np}\ncloudphase:\n{val_cloud_np}"
